name: festappp
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.15.2
  google_sign_in: ^4.1.0
  firebase_storage: ^3.1.0
  font_awesome_flutter: ^8.5.0
  image_picker: ^0.6.2+3
  cached_network_image: ^1.1.3

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

assets:
  - assets/g.jpeg
  - assets/bg.jpg
  - assets/glug.png

fonts:
     - family: BalooBhai-Regular
       fonts:
         - asset: fonts/BalooBhai-Regular.ttf
     - family: Rubik-Bold
       fonts:
         - asset: fonts/Rubik-Bold.ttf
     - family: Rubik-Regular
       fonts:
         - asset: fonts/Rubik-Regular.ttf
